//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid DebugAI = new Guid("57bd5328-bd3b-43fb-a3dc-6d5e7dc070d6");

    }
}
